name: deploy-test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    outputs:
      release_tag: ${{ steps.create_release_action.outputs.tag_name }}
    permissions: 
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0' 

      - name: Restaurar dependências
        run: dotnet restore CarteiradeContatos.sln

      - name: Construir projeto
        run: dotnet build CarteiradeContatos.sln --configuration Release

      - name: Executar testes unitários
        run: dotnet test TestProject/TestProject.csproj --configuration Release

      - name: Publicar projeto
        run: dotnet publish CarteiradeContatos/CarteiradeContatos.csproj -c Release -o ${{ github.workspace }}/publish

      - name: Criar release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: false
          
      - name: Zipar artefato
        uses: thedoctor0/zip-release@master
        with:
          filename: ${{ github.workspace }}/CarteiradeContatos.zip
          directory: ${{ github.workspace }}/publish

      - name: Fazer upload do artefato
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/CarteiradeContatos.zip
          asset_name: CarteiradeContatos.zip
          asset_content_type: application/zip
          
      - name: Debug - Listar saídas
        run: |
            echo "Saídas da ação create_release:"
            echo "Tag: ${{ steps.create_release.outputs.tag_name }}"
            echo "Upload URL: ${{ steps.create_release.outputs.upload_url }}"
          
      - name: Release 1
        if: always()
        run: echo "Tag Release= ${{ needs.create_release.outputs.release_tag }}"
          
      - name: Verificar sucesso da criação do zip
        if: always() || steps.create_release.outputs.upload_url == 'success'
        run: echo "Criação do zip bem-sucedida!"
      
  deploy:
    needs: build
    runs-on: windows-latest
    environment:
      name: test
      url: ${{ steps.deploy_to_azure.outputs.webapp_url }}
    permissions:
      deployments: write
      packages: write
      actions: write
      contents: write
    steps:           
      - name: Download Release Asset
        id: download_release
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const { owner, repo } = context.repo;
            const release_tag = '${{ needs.create_release.outputs.release_tag }}';  
            const asset_name = 'CarteiradeContatos.zip'; 
             const release = await github.rest.repos.getReleaseByTag({
               owner,
               repo,
               tag: release_tag,
             });
            const asset = release.data.assets.find(asset => asset.name === asset_name);
            if (!asset) {
              core.setFailed(`Asset ${asset_name} not found in release ${release_tag}`);
              return;
            }
            const response = await github.request({
             method: 'GET',
             url: asset.url,
             headers: {
               Accept: 'application/octet-stream'
             },
            });
            fs.writeFileSync(asset_name, Buffer.from(response.data));
            core.setOutput('asset_path', asset_name);
            
      - name: Release
        if: always()
        run: echo "Tag Release= ${{ needs.create_release.outputs.release_tag }}"
      
      - name: Deploy to Azure Web App
        id: deploy_to_azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ steps.download_release.outputs.asset_path }}
          
  notify:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Enviar notificação de falha
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Falha no pipeline de CI/CD .NET
          to: victorbm336@hotmail.com
          from: ${{secrets.MAIL_USERNAME}}
          body: O pipeline de CI/CD falhou na etapa ${{ github.job }}. Veja os logs para mais detalhes. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
